import "@wonderland/alice-tokens/dist/css/index.css";
import { useEffect } from "react";
import Head from "next/head";
import Navbar from "@/components/Navbar";
import Banner from "@/components/Banner";

export default function Home() {
  useEffect(() => {
    import("@alice-health/wonderland-react").then(
      ({ defineCustomElements }) => {
        defineCustomElements();
      }
    );
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar blackNavebar={false} />
        <Banner />
      </main>
    </>
  );
}
